### ISSUE TITLE
error: cannot find a hook named pre-commit

### ISSUE THREAD

**Issue by nnamacha** [Lakshmikanth2001/GitHooks#1]
When i try to run the pre-commit git hook VS Code seems to not be able to find it . Although i can see it . What could i be missing

![image](https://user-images.githubusercontent.com/1133995/195791857-6a190df2-4cf0-418a-981c-bf773c3dca1c.png)

**Comment by Lakshmikanth2001** [comment]
sorry for your inconvenience can you let me know your git version
cmd: `git --version`

This mainly happens if your `hook` is inactive. Reload the hooks by pressing the `reload button` on top right and try it again

if you are using git version > `2.36.1`

try cmd: `git hook run pre-commit` through your terminal if you still face the error there is some thing wrong with the `git`  on your local system

please provide your valuable feed back

**Comment by Lakshmikanth2001** [comment]
I think is issue is not active in recent past so I am closing this issue, please feel free to reopen if you are facing any bug
