### ISSUE TITLE
Q&A - Why `GitHooks.hooksDirectory` + monorepo support state

### ISSUE THREAD

**Issue by Malix-off** [Lakshmikanth2001/GitHooks#14]
_This issue would have fit better in a github discussion Q&A, but this repository doesn't have one yet_

Hello!

Why did you choose to feature a `GitHooks.hooksDirectory` setting rather than to force it to `git config core.hooksPath`?
Also, do your extension support multiple repositories in a workspace, such as the monorepo use-case?

Thanks!

**Comment by Lakshmikanth2001** [comment]
- `GitHooks.hooksDirectory` will set `core.hooksPath` for the repository i have chose this to make it a `vscode` setting which can sit in `.vscode` folder and can also be source tracked

- That's a very good question as of now  `no` this extension support only one git project at a time because the tree provider gets only one git repository path and hooks are read from that repo `.git` folder so currently this extension doesn't support multiple git repositories (even vscode workspaces)

any more questions ?

**Comment by Malix-off** [comment]
- Ok 👍
- Okay, would it be possible to support it, or not possible at all?

**Comment by Lakshmikanth2001** [comment]
it's very early to say whether it is possible or not i haven't tried it but i have an idea to have n level `treeDataApiProvider` based on number of folders the workspace has, i will try to included support for this feature, but can't guaranty that i will find out a solution for it  

any more questions ?

**Comment by Malix-off** [comment]
Ok 👍
Following the development closely 😄

**Comment by Lakshmikanth2001** [comment]
Thanks for the suggestion i have released a version 2.0 for the extension which includes workspace support , please review this extension and give your valuable feedback, @Malix-off

**Comment by Malix-off** [comment]
Nice, can you push a release pls?

**Comment by Lakshmikanth2001** [comment]
it's already down please download the latest release

**Comment by Malix-off** [comment]
Nah i'm talking about https://github.com/Lakshmikanth2001/GitHooks/releases

**Comment by Lakshmikanth2001** [comment]
Done, thank for the feature request
