### ISSUE TITLE
Q&A - Why `GitHooks.logLevel` default to `info` rather than `debug`

### ISSUE THREAD

**Issue by Malix-off** [Lakshmikanth2001/GitHooks#15]
_This issue would have fit better in a github discussion Q&A, but this repository doesn't have one yet_

Hello!

Why did you choose `GitHooks.logLevel` to default to `info` rather than `debug`?

Thanks!

**Comment by Lakshmikanth2001** [comment]
because i think , debug is just intended  during development or report any issue so i preferred `INFO` as default value 

- Also point to backup my explanation is python logging module default level is `WARNING` i feel i have very less warning in my extension so i kept it `INFO`

any further questions ?

**Comment by Malix-off** [comment]
Understandable, thanks!
